import {
  Activity,
  Radio,
} from "lucide-react";

import { LiveTelemetryCharts } from "../components/charts/LiveTelemetryCharts";

import { NodeCard } from "../components/dashboard/NodeCard";

import { useLiveStore } from "../store/liveStore";

export default function LiveMonitoring() {
  const nodes =
    useLiveStore(
      (state) =>
        state.nodes
    );

  const connected =
    useLiveStore(
      (state) =>
        state.connected
    );

  const demoMode =
    useLiveStore(
      (state) =>
        state.demoMode
    );

  const simulationActive =
    nodes.some(
      (node) =>
        node.simulated === true ||
        node.source
          ?.trim()
          .toUpperCase() ===
          "SIMULATOR"
    );

  const liveFieldData =
    connected &&
    nodes.some(
      (node) =>
        node.status === "ONLINE" &&
        node.simulated !== true &&
        node.source
          ?.trim()
          .toUpperCase() !==
          "SIMULATOR"
    );

  return (
    <div>
      <div className="page-heading live-page-heading">
        <div>
          <span className="eyebrow">
            REAL-TIME SENSOR NETWORK
          </span>

          <h2>
            Live Monitoring
          </h2>

          <p>
            Turbidity, acoustic, vibration,
            temperature, battery and LoRa
            telemetry from GoldTrace nodes.
          </p>
        </div>

        <div
          className={
            connected
              ? "live-pill"
              : "offline-pill"
          }
        >
          {connected ? (
            <Activity
              size={14}
            />
          ) : (
            <Radio
              size={14}
            />
          )}

          {demoMode
            ? "DEMO LIVE"
            : simulationActive
            ? "SIMULATION ACTIVE"
            : liveFieldData
            ? "FIELD DATA LIVE"
            : connected
            ? "WAITING FOR FIELD DATA"
            : "DISCONNECTED"}
        </div>
      </div>

      {simulationActive && !demoMode && (
        <div className="simulation-source-banner">
          <div>
            <strong>
              SIMULATION ACTIVE
            </strong>

            <span>
              Current telemetry is generated by the
              GoldTrace Simulator.
            </span>
          </div>

          <small>
            Processing remains inside the real GoldTrace
            ML and risk pipeline.
          </small>
        </div>
      )}

      <div className="node-grid">
        {nodes.map(
          (node) => (
            <NodeCard
              key={
                node.node_id
              }
              node={node}
            />
          )
        )}
      </div>

      <div className="dashboard-section">
        <div className="section-title-row">
          <div>
            <span className="eyebrow">
              STREAMING DATA
            </span>

            <h2>
              Sensor Charts
            </h2>
          </div>

          <span className="section-meta">
            Last 40 updates
          </span>
        </div>

        <LiveTelemetryCharts
          nodes={nodes}
        />
      </div>
    </div>
  );
}
